In [2]:
# pip install numpy  pandas

In [3]:
import numpy as np
#ndarray 
#Creating an empty array
#Synatx = numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0) 
empty_ndarray=np.array
print(empty_ndarray)

<built-in function array>


In [9]:
oned_nparray=np.array([1,2,3,4,5])
print(oned_nparray)
print(oned_nparray.shape)
print(oned_nparray.size)
print(oned_nparray.itemsize)
print(oned_nparray.dtype)
print(oned_nparray.reshape(1,5))
print(oned_nparray[3:])

[1 2 3 4 5]
(5,)
5
4
int32
[[1 2 3 4 5]]
[4 5]


In [13]:
two_nparray=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(two_nparray)
print(two_nparray.shape)
print(two_nparray.size)
print(two_nparray.itemsize)
print(two_nparray.dtype)
print(two_nparray.reshape(2,5))
print(two_nparray[1,3])

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
10
4
int32
[[1 2 3 4 5]
 [6 7 8 9 0]]
9


In [15]:
#linspace
print(np.linspace(1,10,20))

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [24]:
print(two_nparray.max(0)) #along columns
print(two_nparray.max()) #Inthe total Array
print(two_nparray.max(1)) #inRows
print(two_nparray.min(0)) #along columns
print(two_nparray.min()) #Inthe total Array
print(two_nparray.min(1))#in rows
print(two_nparray.sum(0)) #along columns
print(two_nparray.sum()) #Inthe total Array
print(two_nparray.sum(1))#in rows
print("SQRT of the ARRAY\n",np.sqrt(two_nparray))
print("\nStandard Deviattion of the ARRAY\n",np.std(two_nparray))

[6 7 8 9 5]
9
[5 9]
[1 2 3 4 0]
0
[1 0]
[ 7  9 11 13  5]
45
[15 30]
SQRT of the ARRAY
 [[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         0.        ]]

Standard Deviattion of the ARRAY
 2.8722813232690143


In [26]:
example1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
example2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
print(example1+example2)
print(example1*example2)
print(example1-example2)
print(example1%example2)
print(example1/example2)
print(example1//example2)

[[12 14 16 18 20]
 [22 24 26 28 30]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444 0.47368421 0.5       ]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [28]:
print(np.vstack((example1,example2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [29]:
print(np.hstack((example1,example2)))

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [30]:
print(np.dstack((example1,example2)))

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]


In [34]:
empty_array=np.empty(shape=(3,2),dtype=int,order='C')
print(empty_array)

[[-1014270352         308]
 [          0           0]
 [     131074 -2147483648]]


In [37]:
zero_array=np.zeros(shape=(3,2),dtype=int)
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [38]:
ones_array=np.ones(shape=(3,2),dtype=int)
print(ones_array)

[[1 1]
 [1 1]
 [1 1]]


In [40]:
li=[1,2,3,4,5,6]
print(np.asarray(li))
print(type(li),"\n",type(np.asarray(li)))

[1 2 3 4 5 6]
<class 'list'> 
 <class 'numpy.ndarray'>


In [44]:
l=[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]  
a = np.asarray(l)  
print(type(a))  
print(a)  

<class 'numpy.ndarray'>
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [45]:
l = b'hello world'  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a))  


<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [47]:
list = [0,2,4,6]
it = iter(list)  
x = np.fromiter(it, dtype = float)
print(x)
print(type(x))

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [48]:
arr = np.linspace(10, 20, 5, endpoint = False)  
print("The array over the given range is ",arr) 

The array over the given range is  [10. 12. 14. 16. 18.]


In [49]:
arr = np.arange(10,100,5,int)  
print("The array over the given range is ",arr)  

The array over the given range is  [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [50]:
arr = np.logspace(10, 20, num = 5,base = 2, endpoint = True)  
print("The array over the given range is ",arr)  

The array over the given range is  [1.02400000e+03 5.79261875e+03 3.27680000e+04 1.85363800e+05
 1.04857600e+06]


In [51]:
#BroadCasting
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_1d = np.array([1, 0, -1])
result = array_2d + array_1d

print(result)

[[2 2 2]
 [5 5 5]
 [8 8 8]]


In [ ]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
print("Printing array:")  
print(a);  
print("Iterating over the array:")  
for x in np.nditer(a):  
    print(x,end=' ')

Printing array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [56]:
#Transpose
at=a.T
print(at)
for i in np.nditer(at):
    print(i,end=" ")

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
1 2 3 4 2 4 5 6 10 20 39 3 

In [60]:
cstype=at.copy(order='C')
print(cstype)
for i in np.nditer(cstype):
    print(i,end=" ")

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
1 2 10 2 4 20 3 5 39 4 6 3 

In [61]:
fstyle=at.copy(order='F')
print(fstyle)
for i in np.nditer(fstyle):
    print(i,end=" ")

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
1 2 3 4 2 4 5 6 10 20 39 3 

In [62]:
for i in np.nditer(a,op_flags=["readwrite"]):
    i[...]=3*i
print(a)

[[  3   6   9  12]
 [  6  12  15  18]
 [ 30  60 117   9]]


In [73]:
# string manupulations
#add
print(np.char.add(['namaste','Hi'], [' to benguluru', ' read python'] ))  

['namaste to benguluru' 'Hi read python']


In [74]:
#multiply
print(np.char.multiply("namaste ",3))  

namaste namaste namaste 


In [75]:
#center
print(np.char.center("namaste", 20, '*'))  

******namaste*******


In [76]:
#capitalize
print(np.char.capitalize("namaste to all")) 

Namaste to all


In [77]:
#title capitalize
print(np.char.title("namaste to all"))  

Namaste To All


In [78]:
#lower
print(np.char.lower("Namaste To All"))  


namaste to all


In [79]:
#upper
print(np.char.upper("namaste to all")) 

NAMASTE TO ALL


In [80]:
#split()
print(np.char.split("Namaste to all"),sep = " ") 

['Namaste', 'to', 'all']


In [81]:
#splitlines()
print(np.char.splitlines("Namaste\nTo\nall")) 

['Namaste', 'To', 'all']


In [82]:
#strip()
print(np.char.strip("   Namaste all"))  


Namaste all


In [83]:
#Mathamatical functions
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("The original array:\n")  
print(a)  
  
  
print("\nThe minimum element among the array:",np.amin(a))  
print("The maximum element among the array:",np.amax(a))  
  
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("The maximum element among the rows of array",np.amax(a,0))  
  
print("\nThe minimum element among the columns of array",np.amin(a,1))  
print("The maximum element among the columns of array",np.amax(a,1)) 

The original array:

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]

The minimum element among the array: 2
The maximum element among the array: 80

The minimum element among the rows of array [ 2 10 10]
The maximum element among the rows of array [80 43 31]

The minimum element among the columns of array [ 2 31 10]
The maximum element among the columns of array [20 80 43]


In [ ]:
#Peak to Peak :: DIfferencr between the max and min
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("Original array:\n",a)  
  
print("\nptp value along axis 1:",np.ptp(a,1))  
  
print("ptp value along axis 0:",np.ptp(a,0))  


Original array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

ptp value along axis 1: [18 49 33]
ptp value along axis 0: [78 33 21]


In [86]:
#percentile :: start+(position×(end−start))
a = np.array([[2,10,20],[80,43,31],[22,43,10]])    
print("Array:\n",a)  
print("\nPercentile along axis 0",np.percentile(a, 10,0))  
print("Percentile along axis 1",np.percentile(a, 10, 1))  

Array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

Percentile along axis 0 [ 6.  16.6 12. ]
Percentile along axis 1 [ 3.6 33.4 12.4]


In [92]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
print(np.mean(a))
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))
print(np.average(a,axis=0))
print(np.average(a,axis=1))
print(np.average(a))

[34.66666667 32.         20.33333333]
[10.66666667 51.33333333 25.        ]
29.0
22.0
[22. 43. 20.]
[10. 43. 22.]
[34.66666667 32.         20.33333333]
[10.66666667 51.33333333 25.        ]
29.0


In [93]:
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
print("Sorting along the columns:")  
print(np.sort(a))  
print("Sorting along the rows:")  
print(np.sort(a, 0))  
data_type = np.dtype([('name', 'S10'),('marks',int)])  
arr = np.array([('Mukesh',200),('John',251)],dtype = data_type)  
print("Sorting data ordered by name")  
print(np.sort(arr,order = 'name'))  

Sorting along the columns:
[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]
Sorting along the rows:
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
Sorting data ordered by name
[(b'John', 251) (b'Mukesh', 200)]


In [94]:
a = np.array([90, 29, 89, 12])  
print("Original array:\n",a)  
sort_ind = np.argsort(a)  
print("Printing indices of sorted data\n",sort_ind)  
sort_a = a[sort_ind]  
print("printing sorted array")    
for i in sort_ind:  
    print(a[i],end = " ")  

Original array:
 [90 29 89 12]
Printing indices of sorted data
 [3 1 2 0]
printing sorted array
12 29 89 90 

In [95]:
a = np.array(['a','b','c','d','e'])  
b = np.array([12, 90, 380, 12, 211])  
ind = np.lexsort((a,b))  
print("printing indices of sorted data")  
print(ind)  
print("using the indices to sort the array")  
for i in ind:  
    print(a[i],b[i])  


printing indices of sorted data
[0 3 1 4 2]
using the indices to sort the array
a 12
d 12
b 90
e 211
c 380


In [96]:
b = np.array([12, 90, 380, 12, 211])  
print("printing original array",b)  
print("printing location of the non-zero elements")  
print(b.nonzero()) 

printing original array [ 12  90 380  12 211]
printing location of the non-zero elements
(array([0, 1, 2, 3, 4], dtype=int64),)


In [97]:
b = np.array([12, 90, 380, 12, 211])  
print(np.where(b>12)) 
c = np.array([[20, 24],[21, 23]])    
print(np.where(c>20))  


(array([1, 2, 4], dtype=int64),)
(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))


In [98]:
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
print("Original Array:\n",a)  
print("\nID of array a:",id(a))  
b = a   
print("\nmaking copy of the array a")  
print("\nID of b:",id(b))  
b.shape = 4,3;  
print("\nChanges on b also reflect to a:")  
print(a)

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 1326286524112

making copy of the array a

ID of b: 1326286524112

Changes on b also reflect to a:
[[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [99]:
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
print("Original Array:\n",a)  
print("\nID of array a:",id(a))  
b = a.view()  
print("\nID of b:",id(b))  
print("\nprinting the view b")  
print(b)  
b.shape = 4,3;  
print("\nChanges made to the view b do not reflect a")  
print("\nOriginal array \n",a)  
print("\nview\n",b)

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 1326287070256

ID of b: 1326281119792

printing the view b
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Changes made to the view b do not reflect a

Original array 
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

view
 [[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [100]:
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
print("Original Array:\n",a)  
print("\nID of array a:",id(a))  
b = a.copy()  
print("\nID of b:",id(b))  
print("\nprinting the deep copy b")  
print(b)
b.shape = 4,3;  
print("\nChanges made to the copy b do not reflect a")  
print("\nOriginal array \n",a)  
print("\nCopy\n",b) 

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 1326286530256

ID of b: 1326287071600

printing the deep copy b
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Changes made to the copy b do not reflect a

Original array 
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Copy
 [[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [109]:
#Matrix library
print(np.matlib.empty((3,3)))
print(np.matlib.zeros((4,3)))
print(np.matlib.ones((2,2)))  

[[2.14321575e-312 2.29175545e-312 6.79038654e-313]
 [2.14321575e-312 2.29175545e-312 6.79038654e-313]
 [2.14321575e-312 2.29175545e-312 6.79038654e-313]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [110]:
print(np.matlib.eye(n = 3, M = 3, k = 0, dtype = int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
print(np.matlib.identity(5, dtype = int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
print(np.matlib.rand(3,3))  

[[0.56888117 0.94923784 0.57474125]
 [0.47113123 0.37108945 0.95797703]
 [0.86167612 0.02729415 0.71229536]]


In [113]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)  

[[3400 6200]
 [ 374  712]]


In [114]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot)  

5528


In [115]:
a = np.array([1,2,3,4,5,6])  
b = np.array([23,23,12,2,1,2])  
inner = np.inner(a,b)  
print(inner)  

130


In [116]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul)  


[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


In [ ]:
a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a))  

-2.0000000000000004


In [ ]:
a = np.array([[1,2],[3,4]])  
b = np.array([[1,2],[3,4]])  
print(np.linalg.solve(a, b))  


[[1.00000000e+00 0.00000000e+00]
 [8.32667268e-17 1.00000000e+00]]


In [ ]:
a = np.array([[1,2],[3,4]])  
print("Original array:\n",a)  
b = np.linalg.inv(a)  
print("Inverse:\n",b)  


Original array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [120]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result=np.multiply(array1,array2)  
result  

array([[[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]]])

In [121]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result=np.matmul(array1,array2)  
result  


array([[[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]])

In [122]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result=np.dot(array1,array2)  
result  

array([[[[ 30,  24,  18]],

        [[ 84,  69,  54]],

        [[138, 114,  90]]]])

In [123]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)  
c  


array([10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31, 42, 52, 62, 73, 83,
       93])

In [124]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=0)  
c  


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [125]:
a=np.unique([1,2,3,4,3,6,2,4])  
a  


array([1, 2, 3, 4, 6])

In [126]:
arr = [0.23, 0.09, 1.2, 1.24, 9.99]  
print("Input array:",arr)  
r_arr = np.trunc(arr)
print("Output array:",r_arr)
arr2 = [145.23, 0.12, 12.34, 123]
r_arr2=np.trunc(arr2)
print("Input array:",arr2)
print("Output array:",r_arr2)

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [0. 0. 1. 1. 9.]
Input array: [145.23, 0.12, 12.34, 123]
Output array: [145.   0.  12. 123.]
