In [3]:
pip  install pandas

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.




[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import pandas as pd
import numpy as np

In [5]:
x = pd.Series()  
print (x)  

Series([], dtype: object)


In [8]:
info = np.array(['P','a','n','d','a','s'])  
a = pd.Series(info)  
print(a)  

0    P
1    a
2    n
3    d
4    a
5    s
dtype: object


In [9]:
info = {'x' : 0., 'y' : 1., 'z' : 2.}  
a = pd.Series(info)  
print (a)  

x    0.0
y    1.0
z    2.0
dtype: float64


In [10]:
x = pd.Series(4, index=[0, 1, 2, 3])  
print (x)  

0    4
1    4
2    4
3    4
dtype: int64


In [12]:
x = pd.Series([1,2,3],index = ['a','b','c'])  
print (x[0]) 

1


C:\Users\suman\AppData\Local\Temp\ipykernel_1240\484470235.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print (x[0])


In [13]:
x=pd.Series(data=[2,4,6,8])   
y=pd.Series(data=[11.2,18.6,22.5], index=['a','b','c'])   
print(x.index)   
print(x.values)   
print(y.index)   
print(y.values) 

RangeIndex(start=0, stop=4, step=1)
[2 4 6 8]
Index(['a', 'b', 'c'], dtype='object')
[11.2 18.6 22.5]


In [20]:
a=pd.Series(data=[1,2,3,4])   
b=pd.Series(data=[4.9,8.2,5.6],index=['x','y','z'])  
print(a.dtype)   
print(b.dtype)   


int64
float64


In [21]:
a=pd.Series(data=[1,2,3,4])   
b=pd.Series(data=[4.9,8.2,5.6],index=['x','y','z'])   
print(a.shape)   
print(b.shape) 

(4,)
(3,)


In [22]:
a=pd.Series(data=[1,2,3,4])   
b=pd.Series(data=[4.9,8.2,5.6],  
index=['x','y','z'])   
print(a.ndim, b.ndim)   
print(a.size, b.size)   
print(a.nbytes, b.nbytes) 

1 1
4 3
32 24


In [23]:
a=pd.Series(data=[1,2,3,np.NaN])   
b=pd.Series(data=[4.9,8.2,5.6],index=['x','y','z'])   
c=pd.Series()   
print(a.empty,b.empty,c.empty)   
print(a.hasnans,b.hasnans,c.hasnans)   
print(len(a),len(b))   
print(a.count( ),b.count( ))  

False False True
True False False
4 3
3 3


In [24]:
a = pd.Series(['Java', 'C', 'C++', np.nan])  
a.map({'Java': 'Core'})  
a.map('I like {}'.format, na_action='ignore') 

0    I like Java
1       I like C
2     I like C++
3            NaN
dtype: object

In [ ]:
a=pd.Series({"a":"1","b":"2","c":"3"})
print(a)

a    1
b    2
c    3
dtype: object


In [28]:
print(np.std([4,7,2,1,6,3]))  
print(np.std([6,9,15,2,-17,15,4]))  

2.1147629234082532
10.077252622027656


In [29]:
#series to frame
s = pd.Series(["a", "b", "c"],  
name="vals")  
s.to_frame()  

vals
0    a
1    b
2    c

In [30]:
emp = ['Parker', 'John', 'Smith', 'William']   
id = [102, 107, 109, 114]     
emp_series = pd.Series(emp)   
id_series = pd.Series(id)     
frame = { 'Emp': emp_series, 'ID': id_series }   
result = pd.DataFrame(frame)     
print(result)  


       Emp   ID
0   Parker  102
1     John  107
2    Smith  109
3  William  114


In [ ]:
pd.unique(pd.Series([2, 1, 3, 3]))

array([2, 1, 3], dtype=int64)

In [32]:
index = pd.Index([2, 1, 1, np.nan, 3])  
index.value_counts() 

1.0    2
2.0    1
3.0    1
Name: count, dtype: int64

In [33]:
df = pd.DataFrame()  
print (df)

Empty DataFrame
Columns: []
Index: []


In [34]:
x = ['Python', 'Pandas']
df = pd.DataFrame(x)  
print(df)  


        0
0  Python
1  Pandas


In [35]:
info = {'ID' :[101, 102, 103],'Department' :['B.Sc','B.Tech','M.Tech',]}  
df = pd.DataFrame(info)  
print (df) 

    ID Department
0  101       B.Sc
1  102     B.Tech
2  103     M.Tech


In [36]:
info = {'one' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f']),'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])}
d1 = pd.DataFrame(info)  
print (d1)  

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8


In [37]:
print (d1 ['one'])

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    NaN
h    NaN
Name: one, dtype: float64


In [42]:
info = {'one' : pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']),'two' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f'])}  
df = pd.DataFrame(info)  
# Add a new column to an existing DataFrame object   
print ("Add new column by passing series")  
df['three']=pd.Series([20,40,60],index=['a','b','c'])  
print (df)  
print ("Add new column using existing DataFrame columns")  
df['four']=df['one']+df['three']  
print (df)
del df['one']  
print (df)
print (df.iloc[3])  


Add new column by passing series
   one  two  three
a  1.0    1   20.0
b  2.0    2   40.0
c  3.0    3   60.0
d  4.0    4    NaN
e  5.0    5    NaN
f  NaN    6    NaN
Add new column using existing DataFrame columns
   one  two  three  four
a  1.0    1   20.0  21.0
b  2.0    2   40.0  42.0
c  3.0    3   60.0  63.0
d  4.0    4    NaN   NaN
e  5.0    5    NaN   NaN
f  NaN    6    NaN   NaN
   two  three  four
a    1   20.0  21.0
b    2   40.0  42.0
c    3   60.0  63.0
d    4    NaN   NaN
e    5    NaN   NaN
f    6    NaN   NaN
two      4.0
three    NaN
four     NaN
Name: d, dtype: float64


In [ ]:
a_info = pd.DataFrame([[4, 5], [6, 7]], columns = ['x','y'])  
b_info = pd.DataFrame([[8, 9], [10, 11]], columns = ['x','y'])
a_info._append(b_info)
a_info = a_info.drop(0)
xxxxxxxxxxxxx
